//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferServiceTester.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorruptedCardInfo
    {
        public long Id { get; set; }
        public string Pan { get; set; }
        public string Cvv2 { get; set; }
        public string Pin2 { get; set; }
        public string ExpDate { get; set; }
    }
}
