//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferServiceTester.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTransactionAmount
    {
        public long Id { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<long> TodayAmountSum { get; set; }
        public long UserId { get; set; }
    }
}
