//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferServiceTester.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PNA_RefundServiceEntities : DbContext
    {
        public PNA_RefundServiceEntities()
            : base("name=PNA_RefundServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CardsInfo> CardsInfo { get; set; }
        public DbSet<CardToCard> CardToCard { get; set; }
        public DbSet<CardTransfer> CardTransfer { get; set; }
        public DbSet<CorruptedCardInfo> CorruptedCardInfo { get; set; }
        public DbSet<DailyTransactionAmount> DailyTransactionAmount { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<NationalCodeInquiry> NationalCodeInquiry { get; set; }
        public DbSet<RefundRequest> RefundRequest { get; set; }
        public DbSet<RefundRequestReconciliation> RefundRequestReconciliation { get; set; }
        public DbSet<ServerInfo> ServerInfo { get; set; }
        public DbSet<Token> Token { get; set; }
        public DbSet<WebServicePermission> WebServicePermission { get; set; }
        public DbSet<WebServiceUser> WebServiceUser { get; set; }
        public DbSet<WebServiceUsersPermission> WebServiceUsersPermission { get; set; }
    
        public virtual ObjectResult<SP_RefundStatistics_Result> SP_RefundStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RefundStatistics_Result>("SP_RefundStatistics");
        }
    }
}
