//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferServiceTester.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> TokenIssueDate { get; set; }
        public string Token1 { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TokenVerifiedDate { get; set; }
    }
}
