//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferServiceTester.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceUser
    {
        public WebServiceUser()
        {
            this.CardsInfo = new HashSet<CardsInfo>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string PublicKey { get; set; }
        public string YaghutUser { get; set; }
        public string YaghutPassword { get; set; }
        public string CustomerAccount { get; set; }
        public string BankAccount { get; set; }
        public string ReverseCardNumber { get; set; }
        public Nullable<long> TransactionMaximumAmount { get; set; }
    
        public virtual ICollection<CardsInfo> CardsInfo { get; set; }
    }
}
