//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTransfer
    {
        public int Id { get; set; }
        public Nullable<long> RefundRefrenceNumber { get; set; }
        public string Status { get; set; }
        public string Rrn { get; set; }
        public Nullable<long> Amount { get; set; }
        public string EncryptedSourcePan { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<int> SourceCardId { get; set; }
    
        public virtual RefundRequest RefundRequest { get; set; }
    }
}
