//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBANTransfer
    {
        public long Id { get; set; }
        public Nullable<long> RefundRefrenceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<long> TransferId { get; set; }
        public Nullable<long> Amount { get; set; }
        public string EncryptedIBAN { get; set; }
        public string EncryptedPan { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<long> InquiryCommision { get; set; }
    }
}
