//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public string FunctionName { get; set; }
        public Nullable<long> RefrenceNumber { get; set; }
        public string Rrn { get; set; }
        public Nullable<long> Amount { get; set; }
        public string MaskedDestinationPan { get; set; }
        public string RefundDescription { get; set; }
        public string Type { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public string UserName { get; set; }
    }
}
