//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NationalCodeInquiry
    {
        public long Id { get; set; }
        public Nullable<long> ResponseCode { get; set; }
        public string NationalCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string BirthDate { get; set; }
        public string ShenasnameSerial { get; set; }
        public string ShenasnameNo { get; set; }
        public string ShenasnameSeri { get; set; }
        public Nullable<int> DeathStatus { get; set; }
        public Nullable<int> GenderStatus { get; set; }
        public string Description { get; set; }
    }
}
