//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundTransferService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebServiceUser()
        {
            this.CardsInfo = new HashSet<CardsInfo>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string PublicKey { get; set; }
        public string YaghutUser { get; set; }
        public string YaghutPassword { get; set; }
        public string CustomerAccount { get; set; }
        public string BankAccount { get; set; }
        public string ReverseCardNumber { get; set; }
        public Nullable<long> TransactionMaximumAmount { get; set; }
        public Nullable<int> ProviderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardsInfo> CardsInfo { get; set; }
        public virtual RefundProvider RefundProvider { get; set; }
    }
}
